name: Deploy to Azure Static Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./crmbly-web

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ./crmbly-web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOY_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "crmbly-web/dist"
          api_location: ""
          output_location: ""
          skip_app_build: true
        env:
          NODE_VERSION: "20"

