name: PR Verify IaC

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "terraform/**"
      - ".github/workflows/pr-verify-iac.yml"

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform:
    name: "Terraform - ${{ matrix.environment }}"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    strategy:
      matrix:
        environment: [prod]
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=crmbly-tfstate" \
            -backend-config="storage_account_name=crmblytfstate" \
            -backend-config="container_name=${{ matrix.environment }}-tfstate" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ matrix.environment }}"

      - name: Terraform Validate
        run: terraform validate

